"""
Runs the scraper layer ONLY (no LLM, no W&B key) and stores everything it finds
into a single markdown knowledge-base file the research agent can consume offline.

Scrapes:
  - OWASP Top 10 for LLM Applications
  - MITRE ATLAS techniques (live, from atlas.mitre.org)
  - Per-domain open-web threat intel (DuckDuckGo) for every target profile

Usage:
    python3 build_research_kb.py                 # -> research_kb.md
    python3 build_research_kb.py --out my.md
    python3 build_research_kb.py --no-web         # frameworks only (skip DuckDuckGo)
"""

import argparse
import datetime as _dt

from profiles import TARGET_PROFILES
from web_search import fetch_owasp_llm_top10, fetch_mitre_atlas_techniques, web_search


def build_markdown(include_web: bool = True) -> str:
    now = _dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    out = [
        "# Research Agent Knowledge Base",
        "",
        f"_Auto-generated by `build_research_kb.py` on {now}. Scraper output only — no LLM synthesis._",
        "",
        "---",
        "",
        "## 1. Authoritative Frameworks",
        "",
    ]

    # ── OWASP ─────────────────────────────────────────────────────────────────────
    owasp = fetch_owasp_llm_top10()
    out.append(f"### OWASP Top 10 for LLM Applications")
    out.append(f"Source: <{owasp['url']}>")
    out.append("")
    if owasp["items"]:
        out += [f"- **{x}**" for x in owasp["items"]]
    else:
        out.append("_(scrape returned no items)_")
    out.append("")

    # ── MITRE ATLAS ───────────────────────────────────────────────────────────────
    atlas = fetch_mitre_atlas_techniques()
    out.append(f"### MITRE ATLAS Techniques ({len(atlas['items'])})")
    out.append(f"Source: <{atlas['url']}>")
    out.append("")
    if atlas["items"]:
        out += [f"- `{it['id']}` — {it['name']}" for it in atlas["items"]]
    else:
        out.append("_(scrape returned no items)_")
    out.append("")
    out.append("---")
    out.append("")

    # ── Per-domain open-web intel ──────────────────────────────────────────────────
    out.append("## 2. Domain Threat Intelligence (open web)")
    out.append("")
    if not include_web:
        out.append("_Skipped (--no-web)._")
        out.append("")
        return "\n".join(out)

    for name, profile in TARGET_PROFILES.items():
        out.append(f"### {name}")
        out.append(f"_Domain: {profile.get('domain', 'n/a')}_")
        out.append("")
        for q in profile.get("research_queries", []):
            out.append(f"#### Query: `{q}`")
            hits = web_search(q, max_results=4)
            if not hits:
                out.append("- _(no results — rate-limited or no network)_")
            for h in hits:
                title = h["title"] or "(untitled)"
                url = h["url"]
                snippet = (h["snippet"] or "").replace("\n", " ").strip()
                out.append(f"- [{title}]({url})")
                if snippet:
                    out.append(f"  - {snippet}")
            out.append("")

    return "\n".join(out)


def main() -> None:
    ap = argparse.ArgumentParser(description="Scrape sources into a research knowledge-base markdown file.")
    ap.add_argument("--out", default="research_kb.md", help="Output markdown path (default: research_kb.md)")
    ap.add_argument("--no-web", action="store_true", help="Frameworks only — skip the DuckDuckGo per-domain scrape.")
    args = ap.parse_args()

    print("Scraping frameworks + open web (this can take ~30-60s)…")
    md = build_markdown(include_web=not args.no_web)
    with open(args.out, "w") as f:
        f.write(md)
    print(f"✓ wrote {len(md):,} chars to {args.out}")


if __name__ == "__main__":
    main()
